from . import lucky_handler
from . import save_phrase_handler
from . import show_all_phrase_handler
from . import show_my_phrase_handler
from . import weather_handler
from . import search_handler
from . import help_edit_handler
from . import horoscope_handler
from . import rate_handler
from . import advice_handler
from . import active_handler
